"""fixed the column name

Revision ID: 428c24b710a9
Revises: 3048cb39d849
Create Date: 2025-12-11 14:12:03.738994

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '428c24b710a9'
down_revision: Union[str, Sequence[str], None] = '3048cb39d849'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('clients', schema=None) as batch_op:
        batch_op.add_column(sa.Column('insurance_provider', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('insurance_coverage_policy', sa.Integer(), nullable=False))
        batch_op.drop_column('insurence_provider')
        batch_op.drop_column('insurence_coverage_policy')

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('clients', schema=None) as batch_op:
        batch_op.add_column(sa.Column('insurence_coverage_policy', sa.INTEGER(), nullable=False))
        batch_op.add_column(sa.Column('insurence_provider', sa.VARCHAR(), nullable=True))
        batch_op.drop_column('insurance_coverage_policy')
        batch_op.drop_column('insurance_provider')

    # ### end Alembic commands ###
