"""added client relationship with users added user roles

Revision ID: 53cc595fc66a
Revises: 858cb3a3009e
Create Date: 2025-12-11 11:07:52.573094

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '53cc595fc66a'
down_revision: Union[str, Sequence[str], None] = '858cb3a3009e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('clients',
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('date_of_birth', sa.DateTime(), nullable=False),
    sa.Column('case_status', sa.Boolean(), nullable=False),
    sa.Column('insurence_provider', sa.String(), nullable=True),
    sa.Column('active_cases', sa.Integer(), nullable=True),
    sa.Column('gender', sa.Enum('male', 'female', 'other', name='genderenum'), nullable=False),
    sa.Column('insurence_coverage_policy', sa.Integer(), nullable=False),
    sa.Column('id_number', sa.String(), nullable=False),
    sa.Column('primary_contact_number', sa.String(length=20), nullable=True),
    sa.Column('secondary_contact_number', sa.String(length=20), nullable=True),
    sa.Column('key_contact_name', sa.String(), nullable=True),
    sa.Column('contact_person_phone', sa.String(length=20), nullable=True),
    sa.Column('home_address', sa.String(length=300), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('client_id')
    )
    with op.batch_alter_table('clients', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_clients_client_id'), ['client_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_clients_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_clients_name'), ['name'], unique=False)

    with op.batch_alter_table('Client', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_Client_client_id'))
        batch_op.drop_index(batch_op.f('ix_Client_email'))
        batch_op.drop_index(batch_op.f('ix_Client_name'))

    op.drop_table('Client')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('role', sa.Enum('admin', 'superadmin', 'staff', 'editor', 'viewer', name='roleenum'), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('role')

    op.create_table('Client',
    sa.Column('client_id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(), nullable=False),
    sa.Column('date_of_birth', sa.DATETIME(), nullable=False),
    sa.Column('case_status', sa.BOOLEAN(), nullable=False),
    sa.Column('insurence_provider', sa.VARCHAR(), nullable=True),
    sa.Column('active_cases', sa.INTEGER(), nullable=True),
    sa.Column('gender', sa.VARCHAR(length=6), nullable=False),
    sa.Column('insurence_coverage_policy', sa.INTEGER(), nullable=False),
    sa.Column('id_number', sa.INTEGER(), nullable=False),
    sa.Column('primary_contact_number', sa.INTEGER(), nullable=True),
    sa.Column('secondary_contact_number', sa.INTEGER(), nullable=True),
    sa.Column('key_contact_name', sa.VARCHAR(), nullable=True),
    sa.Column('contact_person_phone', sa.INTEGER(), nullable=True),
    sa.Column('home_address', sa.VARCHAR(length=300), nullable=True),
    sa.Column('email', sa.VARCHAR(), nullable=True),
    sa.PrimaryKeyConstraint('client_id')
    )
    with op.batch_alter_table('Client', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_Client_name'), ['name'], unique=False)
        batch_op.create_index(batch_op.f('ix_Client_email'), ['email'], unique=1)
        batch_op.create_index(batch_op.f('ix_Client_client_id'), ['client_id'], unique=False)

    with op.batch_alter_table('clients', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_clients_name'))
        batch_op.drop_index(batch_op.f('ix_clients_email'))
        batch_op.drop_index(batch_op.f('ix_clients_client_id'))

    op.drop_table('clients')
    # ### end Alembic commands ###
