"""initial migration

Revision ID: 858cb3a3009e
Revises: 
Create Date: 2025-12-10 18:09:31.462480

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '858cb3a3009e'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Client',
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('date_of_birth', sa.DateTime(), nullable=False),
    sa.Column('case_status', sa.Boolean(), nullable=False),
    sa.Column('insurence_provider', sa.String(), nullable=True),
    sa.Column('active_cases', sa.Integer(), nullable=True),
    sa.Column('gender', sa.Enum('male', 'female', 'other', name='genderenum'), nullable=False),
    sa.Column('insurence_coverage_policy', sa.Integer(), nullable=False),
    sa.Column('id_number', sa.Integer(), nullable=False),
    sa.Column('primary_contact_number', sa.Integer(), nullable=True),
    sa.Column('secondary_contact_number', sa.Integer(), nullable=True),
    sa.Column('key_contact_name', sa.String(), nullable=True),
    sa.Column('contact_person_phone', sa.Integer(), nullable=True),
    sa.Column('home_address', sa.String(length=300), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('client_id')
    )
    with op.batch_alter_table('Client', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_Client_client_id'), ['client_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_Client_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_Client_name'), ['name'], unique=False)

    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('hashed_password', sa.String(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_users_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_users_username'), ['username'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_username'))
        batch_op.drop_index(batch_op.f('ix_users_id'))
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    with op.batch_alter_table('Client', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_Client_name'))
        batch_op.drop_index(batch_op.f('ix_Client_email'))
        batch_op.drop_index(batch_op.f('ix_Client_client_id'))

    op.drop_table('Client')
    # ### end Alembic commands ###
