"""added profile pic url field

Revision ID: a9cb7109d4d2
Revises: 428c24b710a9
Create Date: 2025-12-12 12:55:33.102987

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a9cb7109d4d2'
down_revision: Union[str, Sequence[str], None] = '428c24b710a9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('clients', schema=None) as batch_op:
        batch_op.add_column(sa.Column('profile_image', sa.String(), nullable=True))
        batch_op.drop_index(batch_op.f('ix_clients_email'))
        batch_op.create_index(batch_op.f('ix_clients_email'), ['email'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('clients', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_clients_email'))
        batch_op.create_index(batch_op.f('ix_clients_email'), ['email'], unique=1)
        batch_op.drop_column('profile_image')

    # ### end Alembic commands ###
